use_frameworks!

platform :ios, '10.0'

install! 'cocoapods', :deterministic_uuids => false

target 'DigitalIDCardBagSDK_Example' do
  pod 'DigitalIDCardBagSDK', :path => '../'

  target 'DigitalIDCardBagSDK_Tests' do
    inherit! :search_paths

    
  end
end
